site_name: NovaCity Rolplay
theme :
  name: material
  #logo: assets/logo.png
  #favicon: images/favicon.png
  
  extra:
    homepage: https://www.novacity-rp.nl
  
  font:
    text: Roboto
  
  palette: 
    scheme: slate
    primary: deep purple
     
        
  features:
      - navigation.instant
      - navigation.instant.progress
      - navigation.instant.preview
      - navigation.tracking
      - navigation.tabs
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.sections
      - navigation.expand
      - navigation.top
      - search.sugest
      - search.highlight
      - search.share
  
  plugins:
    - search
    - tags
  markdown_extensions:
    - tables

nav:
  - Home: index.md
  - Informatie: informatie.md    
  - Algemene Plaatselijke Verordening: apv.md    